Include cloth-config-fabric since we rely on it for ModConfig
Without this, we crash at load time with java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData